const INVALID_DATA_ERROR = 400;

const NOTFOUND_ERROR = 404;

const DEFAULT_ERROR = 500;

const CONFLICT_ERROR = 409;

const FORBIDDEN_ERROR = 403;

const REQUEST_SUCCESSFUL = 200;

const UNAUTHORIZED_ERROR = 401;

module.exports = {
  INVALID_DATA_ERROR,
  NOTFOUND_ERROR,
  DEFAULT_ERROR,
  CONFLICT_ERROR,
  FORBIDDEN_ERROR,
  REQUEST_SUCCESSFUL,
  UNAUTHORIZED_ERROR,
};
